### ISSUE TITLE
always results into "tasks did not start succesfully" - "waiter has timed out"

### ISSUE THREAD

**Issue by simllll** [geekcell/github-action-aws-ecs-run-task#33]
Thanks for the gh action!
Unfortunately I have one (major) issue with it. I'm using the latest version (5.0.1) of your gh action.

it always tells me that the wait has timed out,...
`Task did not start successfully. Error: {"state":"TIMEOUT","reason":"Waiter has timed out"}.`

My task only runs for about 10 seconds, my current config looks like the following:
```
       - name: Run db migration
          id: run-task
          uses: geekcell/github-action-aws-ecs-run-task@v5.0.1
          with:
            cluster: ..
            task-definition: ...
            subnet-ids: ...
            security-group-ids: |
              sg-..
              sg-..
            assign-public-ip: 'DISABLED'
            task-wait-until-stopped: true
            tail-logs: true
            task-check-state-delay: 2

```

tail-logs does output my logs, the task completes. the ecs task moves to stopped.. but the gh action still waits, till the mentioned error message pops up.

even if i do not set tail-logs it actually outputs my logs..? is this intended?

I played around with excplicity settings things to false and setting `task-check-state-delay` to different values.
```
task-wait-until-stopped: false
tail-logs: false
```
but no luck so far :/
`Error: Task did not start successfully. Error: {"state":"TIMEOUT","reason":"Waiter has timed out"}.
`

I'm starting a ecs task in fargate, tasks lifecycle is:
PENDING -> RUNNING (for about 10-15 seconds) -> STOPPED

any idea whats going on?
